/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CabasPersonnaliseRouteImport } from './routes/cabas-personnalise'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as EspaceProRouteImport } from './routes/espace-pro'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as PersonnalisesRouteImport } from './routes/personnalises'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as LegalPageRouteImport } from './routes/legal.$page'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as QuestionsIndexRouteImport } from './routes/questions/index'
import { Route as QuestionsResultatsRouteImport } from './routes/questions/resultats'
import { Route as RayonRayonRouteImport } from './routes/rayon.$rayon'
import { Route as StyleIndexRouteImport } from './routes/style/index'
import { Route as StyleResultatsRouteImport } from './routes/style/resultats'
import { Route as TextesResultatsRouteImport } from './routes/textes/resultats'
import { Route as TriIndexRouteImport } from './routes/tri/index'
import { Route as TriResultatsRouteImport } from './routes/tri/resultats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CabasPersonnaliseRoute = CabasPersonnaliseRouteImport.update({
  id: '/cabas-personnalise',
  path: '/cabas-personnalise',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceProRoute = EspaceProRouteImport.update({
  id: '/espace-pro',
  path: '/espace-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnalisesRoute = PersonnalisesRouteImport.update({
  id: '/personnalises',
  path: '/personnalises',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPageRoute = LegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsIndexRoute = QuestionsIndexRouteImport.update({
  id: '/questions/',
  path: '/questions/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionsResultatsRoute = QuestionsResultatsRouteImport.update({
  id: '/questions/resultats',
  path: '/questions/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const RayonRayonRoute = RayonRayonRouteImport.update({
  id: '/rayon/$rayon',
  path: '/rayon/$rayon',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleIndexRoute = StyleIndexRouteImport.update({
  id: '/style/',
  path: '/style/',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleResultatsRoute = StyleResultatsRouteImport.update({
  id: '/style/resultats',
  path: '/style/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const TextesResultatsRoute = TextesResultatsRouteImport.update({
  id: '/textes/resultats',
  path: '/textes/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const TriIndexRoute = TriIndexRouteImport.update({
  id: '/tri/',
  path: '/tri/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriResultatsRoute = TriResultatsRouteImport.update({
  id: '/tri/resultats',
  path: '/tri/resultats',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/questions/resultats': typeof QuestionsResultatsRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/style/resultats': typeof StyleResultatsRoute
  '/textes/resultats': typeof TextesResultatsRoute
  '/tri/resultats': typeof TriResultatsRoute
  '/questions/': typeof QuestionsIndexRoute
  '/style/': typeof StyleIndexRoute
  '/tri/': typeof TriIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/questions/resultats': typeof QuestionsResultatsRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/style/resultats': typeof StyleResultatsRoute
  '/textes/resultats': typeof TextesResultatsRoute
  '/tri/resultats': typeof TriResultatsRoute
  '/questions': typeof QuestionsIndexRoute
  '/style': typeof StyleIndexRoute
  '/tri': typeof TriIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/questions/resultats': typeof QuestionsResultatsRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/style/resultats': typeof StyleResultatsRoute
  '/textes/resultats': typeof TextesResultatsRoute
  '/tri/resultats': typeof TriResultatsRoute
  '/questions/': typeof QuestionsIndexRoute
  '/style/': typeof StyleIndexRoute
  '/tri/': typeof TriIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/legal/$page'
    | '/produit/$slug'
    | '/questions/resultats'
    | '/rayon/$rayon'
    | '/style/resultats'
    | '/textes/resultats'
    | '/tri/resultats'
    | '/questions/'
    | '/style/'
    | '/tri/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/legal/$page'
    | '/produit/$slug'
    | '/questions/resultats'
    | '/rayon/$rayon'
    | '/style/resultats'
    | '/textes/resultats'
    | '/tri/resultats'
    | '/questions'
    | '/style'
    | '/tri'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/legal/$page'
    | '/produit/$slug'
    | '/questions/resultats'
    | '/rayon/$rayon'
    | '/style/resultats'
    | '/textes/resultats'
    | '/tri/resultats'
    | '/questions/'
    | '/style/'
    | '/tri/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CabasPersonnaliseRoute: typeof CabasPersonnaliseRoute
  CommandeRoute: typeof CommandeRoute
  ComposerRoute: typeof ComposerRoute
  EspaceProRoute: typeof EspaceProRoute
  LivraisonRoute: typeof LivraisonRoute
  PersonnalisesRoute: typeof PersonnalisesRoute
  RechercheRoute: typeof RechercheRoute
  LegalPageRoute: typeof LegalPageRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  QuestionsResultatsRoute: typeof QuestionsResultatsRoute
  RayonRayonRoute: typeof RayonRayonRoute
  StyleResultatsRoute: typeof StyleResultatsRoute
  TextesResultatsRoute: typeof TextesResultatsRoute
  TriResultatsRoute: typeof TriResultatsRoute
  QuestionsIndexRoute: typeof QuestionsIndexRoute
  StyleIndexRoute: typeof StyleIndexRoute
  TriIndexRoute: typeof TriIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabas-personnalise': {
      id: '/cabas-personnalise'
      path: '/cabas-personnalise'
      fullPath: '/cabas-personnalise'
      preLoaderRoute: typeof CabasPersonnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-pro': {
      id: '/espace-pro'
      path: '/espace-pro'
      fullPath: '/espace-pro'
      preLoaderRoute: typeof EspaceProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnalises': {
      id: '/personnalises'
      path: '/personnalises'
      fullPath: '/personnalises'
      preLoaderRoute: typeof PersonnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$page': {
      id: '/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof LegalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/': {
      id: '/questions/'
      path: '/questions'
      fullPath: '/questions/'
      preLoaderRoute: typeof QuestionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questions/resultats': {
      id: '/questions/resultats'
      path: '/questions/resultats'
      fullPath: '/questions/resultats'
      preLoaderRoute: typeof QuestionsResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rayon/$rayon': {
      id: '/rayon/$rayon'
      path: '/rayon/$rayon'
      fullPath: '/rayon/$rayon'
      preLoaderRoute: typeof RayonRayonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style/': {
      id: '/style/'
      path: '/style'
      fullPath: '/style/'
      preLoaderRoute: typeof StyleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/style/resultats': {
      id: '/style/resultats'
      path: '/style/resultats'
      fullPath: '/style/resultats'
      preLoaderRoute: typeof StyleResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/textes/resultats': {
      id: '/textes/resultats'
      path: '/textes/resultats'
      fullPath: '/textes/resultats'
      preLoaderRoute: typeof TextesResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri/': {
      id: '/tri/'
      path: '/tri'
      fullPath: '/tri/'
      preLoaderRoute: typeof TriIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri/resultats': {
      id: '/tri/resultats'
      path: '/tri/resultats'
      fullPath: '/tri/resultats'
      preLoaderRoute: typeof TriResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CabasPersonnaliseRoute: CabasPersonnaliseRoute,
  CommandeRoute: CommandeRoute,
  ComposerRoute: ComposerRoute,
  EspaceProRoute: EspaceProRoute,
  LivraisonRoute: LivraisonRoute,
  PersonnalisesRoute: PersonnalisesRoute,
  RechercheRoute: RechercheRoute,
  LegalPageRoute: LegalPageRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  QuestionsResultatsRoute: QuestionsResultatsRoute,
  RayonRayonRoute: RayonRayonRoute,
  StyleResultatsRoute: StyleResultatsRoute,
  TextesResultatsRoute: TextesResultatsRoute,
  TriResultatsRoute: TriResultatsRoute,
  QuestionsIndexRoute: QuestionsIndexRoute,
  StyleIndexRoute: StyleIndexRoute,
  TriIndexRoute: TriIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
