/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtelierRouteImport } from './routes/atelier'
import { Route as CabasPersonnaliseRouteImport } from './routes/cabas-personnalise'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ComposerRouteImport } from './routes/composer'
import { Route as EspaceProRouteImport } from './routes/espace-pro'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as PersonnalisesRouteImport } from './routes/personnalises'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as TriRouteImport } from './routes/tri'
import { Route as LegalPageRouteImport } from './routes/legal.$page'
import { Route as ProduitSlugRouteImport } from './routes/produit.$slug'
import { Route as RayonRayonRouteImport } from './routes/rayon.$rayon'
import { Route as TriResultatsRouteImport } from './routes/tri/resultats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtelierRoute = AtelierRouteImport.update({
  id: '/atelier',
  path: '/atelier',
  getParentRoute: () => rootRouteImport,
} as any)
const CabasPersonnaliseRoute = CabasPersonnaliseRouteImport.update({
  id: '/cabas-personnalise',
  path: '/cabas-personnalise',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposerRoute = ComposerRouteImport.update({
  id: '/composer',
  path: '/composer',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceProRoute = EspaceProRouteImport.update({
  id: '/espace-pro',
  path: '/espace-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnalisesRoute = PersonnalisesRouteImport.update({
  id: '/personnalises',
  path: '/personnalises',
  getParentRoute: () => rootRouteImport,
} as any)
const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const TriRoute = TriRouteImport.update({
  id: '/tri',
  path: '/tri',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPageRoute = LegalPageRouteImport.update({
  id: '/legal/$page',
  path: '/legal/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitSlugRoute = ProduitSlugRouteImport.update({
  id: '/produit/$slug',
  path: '/produit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RayonRayonRoute = RayonRayonRouteImport.update({
  id: '/rayon/$rayon',
  path: '/rayon/$rayon',
  getParentRoute: () => rootRouteImport,
} as any)
const TriResultatsRoute = TriResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => TriRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/tri': typeof TriRouteWithChildren
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/tri/resultats': typeof TriResultatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/tri': typeof TriRouteWithChildren
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/tri/resultats': typeof TriResultatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atelier': typeof AtelierRoute
  '/cabas-personnalise': typeof CabasPersonnaliseRoute
  '/commande': typeof CommandeRoute
  '/composer': typeof ComposerRoute
  '/espace-pro': typeof EspaceProRoute
  '/livraison': typeof LivraisonRoute
  '/personnalises': typeof PersonnalisesRoute
  '/recherche': typeof RechercheRoute
  '/tri': typeof TriRouteWithChildren
  '/legal/$page': typeof LegalPageRoute
  '/produit/$slug': typeof ProduitSlugRoute
  '/rayon/$rayon': typeof RayonRayonRoute
  '/tri/resultats': typeof TriResultatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/tri'
    | '/legal/$page'
    | '/produit/$slug'
    | '/rayon/$rayon'
    | '/tri/resultats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/tri'
    | '/legal/$page'
    | '/produit/$slug'
    | '/rayon/$rayon'
    | '/tri/resultats'
  id:
    | '__root__'
    | '/'
    | '/atelier'
    | '/cabas-personnalise'
    | '/commande'
    | '/composer'
    | '/espace-pro'
    | '/livraison'
    | '/personnalises'
    | '/recherche'
    | '/tri'
    | '/legal/$page'
    | '/produit/$slug'
    | '/rayon/$rayon'
    | '/tri/resultats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtelierRoute: typeof AtelierRoute
  CabasPersonnaliseRoute: typeof CabasPersonnaliseRoute
  CommandeRoute: typeof CommandeRoute
  ComposerRoute: typeof ComposerRoute
  EspaceProRoute: typeof EspaceProRoute
  LivraisonRoute: typeof LivraisonRoute
  PersonnalisesRoute: typeof PersonnalisesRoute
  RechercheRoute: typeof RechercheRoute
  TriRoute: typeof TriRouteWithChildren
  LegalPageRoute: typeof LegalPageRoute
  ProduitSlugRoute: typeof ProduitSlugRoute
  RayonRayonRoute: typeof RayonRayonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atelier': {
      id: '/atelier'
      path: '/atelier'
      fullPath: '/atelier'
      preLoaderRoute: typeof AtelierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabas-personnalise': {
      id: '/cabas-personnalise'
      path: '/cabas-personnalise'
      fullPath: '/cabas-personnalise'
      preLoaderRoute: typeof CabasPersonnaliseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composer': {
      id: '/composer'
      path: '/composer'
      fullPath: '/composer'
      preLoaderRoute: typeof ComposerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace-pro': {
      id: '/espace-pro'
      path: '/espace-pro'
      fullPath: '/espace-pro'
      preLoaderRoute: typeof EspaceProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnalises': {
      id: '/personnalises'
      path: '/personnalises'
      fullPath: '/personnalises'
      preLoaderRoute: typeof PersonnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri': {
      id: '/tri'
      path: '/tri'
      fullPath: '/tri'
      preLoaderRoute: typeof TriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$page': {
      id: '/legal/$page'
      path: '/legal/$page'
      fullPath: '/legal/$page'
      preLoaderRoute: typeof LegalPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$slug': {
      id: '/produit/$slug'
      path: '/produit/$slug'
      fullPath: '/produit/$slug'
      preLoaderRoute: typeof ProduitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rayon/$rayon': {
      id: '/rayon/$rayon'
      path: '/rayon/$rayon'
      fullPath: '/rayon/$rayon'
      preLoaderRoute: typeof RayonRayonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tri/resultats': {
      id: '/tri/resultats'
      path: '/resultats'
      fullPath: '/tri/resultats'
      preLoaderRoute: typeof TriResultatsRouteImport
      parentRoute: typeof TriRoute
    }
  }
}

interface TriRouteChildren {
  TriResultatsRoute: typeof TriResultatsRoute
}

const TriRouteChildren: TriRouteChildren = {
  TriResultatsRoute: TriResultatsRoute,
}

const TriRouteWithChildren = TriRoute._addFileChildren(TriRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtelierRoute: AtelierRoute,
  CabasPersonnaliseRoute: CabasPersonnaliseRoute,
  CommandeRoute: CommandeRoute,
  ComposerRoute: ComposerRoute,
  EspaceProRoute: EspaceProRoute,
  LivraisonRoute: LivraisonRoute,
  PersonnalisesRoute: PersonnalisesRoute,
  RechercheRoute: RechercheRoute,
  TriRoute: TriRouteWithChildren,
  LegalPageRoute: LegalPageRoute,
  ProduitSlugRoute: ProduitSlugRoute,
  RayonRayonRoute: RayonRayonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
